CREATE DATABASE CRUD_NODE2;

USE CRUD_NODE2;


CREATE TABLE personas(
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(150),
    TELEFONO VARCHAR(10),
    PRIMARY KEY(ID)
)

INSERT INTO PERSONAS(NOMBRE, DIRECCION, TELEFONO)
VALUES ('JUAN LOPEZ', 'SU DIRECCION', '6612345678')